FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

ARG VITE_MAX_IMAGE_HEIGHT
ENV VITE_MAX_IMAGE_HEIGHT=$VITE_MAX_IMAGE_HEIGHT

RUN npm ci --omit=dev

COPY . .

EXPOSE 3001

CMD ["npm", "start"]